services:
  djangoapp:
    container_name: djangoapp
    restart: always
    env_file: 
      - .env
    build: .
    ports:
      - "8000:8000"
    environment:
      - PG_USER=postgres
      - PG_PASSWORD=postgres
      - PG_DB=postgres
      - PG_HOST=db
      - PG_PORT=5432
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis
    volumes:
      - .:/app

  db:
    container_name: salmini_db
    image: postgis/postgis:15-3.3
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: redis:6.2
    ports:
      - "6379:6379"

  # celery:
  #   container_name: celery
  #   build: .
  #   command: celery -A your_project worker --loglevel=info
  #   environment:
  #     - CELERY_BROKER_URL=redis://redis:6379/0
  #   volumes:
  #     - .:/app
  #   depends_on:
  #     - djangoapp
  #     - redis

  # celery_beat:
  #   container_name: celery_beat
  #   build: .
  #   command: celery -A your_project beat --loglevel=info
  #   environment:
  #     - CELERY_BROKER_URL=redis://redis:6379/0
  #   volumes:
  #     - .:/app
  #   depends_on:
  #     - djangoapp
  #     - redis

volumes:
  pgdata: {}